# SPDX-License-Identifier: GPL-2.0

DTC_FLAGS += -@
dtb-$(CONFIG_ARCH_MXC) += imx8mp-debix-lora-board.dtbo
dtb-$(CONFIG_ARCH_MXC) += imx8mp-debix-4g-board.dtbo
dtb-$(CONFIG_ARCH_MXC) += imx8mp-debix-core-ov5640.dtbo
dtb-$(CONFIG_ARCH_MXC) += imx8mp-debix-core-gc2145.dtbo
dtb-$(CONFIG_ARCH_MXC) += imx8mp-debix-core-ar1335.dtbo
dtb-$(CONFIG_ARCH_MXC) += imx8mp-debix-core-TD050A.dtbo
dtb-$(CONFIG_ARCH_MXC) += imx8mp-debix-core-TD060A.dtbo
dtb-$(CONFIG_ARCH_MXC) += imx8mp-debix-core-TD070A.dtbo
dtb-$(CONFIG_ARCH_MXC) += imx8mp-debix-core-TD080A.dtbo
dtb-$(CONFIG_ARCH_MXC) += imx8mp-debix-core-TD080B.dtbo
dtb-$(CONFIG_ARCH_MXC) += imx8mp-debix-core-TD101A.dtbo


